title: Pico-SDK-JS
description: Pico-SDK-JS brings JavaScript to the Raspberry Pi Pico, simplifying development and testing with direct access to many Pico-SDK C functions.
theme: just-the-docs
logo: "assets/images/logo.webp"
favicon_ico: "assets/images/favicon.ico"

url: https://pico-sdk-js.github.io
