name: CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: "pages-ci"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: NPM Install
        run: npm install

      - name: Build with Jekyll
        run: npm run ci-build

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: build-artifact
          path: |
            _data/**
            _site/**
          retention-days: 1
    