name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Create Settings Data File
        uses: jsdaniell/create-json@v1.2.3
        with:
          json: '{ "applicationInsights": "${{ vars.APPINSIGHTS_CONNECTIONSTRING }}" }'
          name: '_data/settings.json'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: NPM Install
        run: npm install

      - name: Build with Jekyll
        run: npm run ci-build
        env:
          JEKYLL_ENV: production

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: build-artifact
          path: |
            _data/**
            _site/**
          retention-days: 3

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
